load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")

mediapipe_aar(
    name = "mediapipe_template_matching",
    calculators = ["//mediapipe/graphs/template_matching:mobile_calculators"],
)
